### ISSUE TITLE
[Question]: Should we enforce time zone aware datetimes everywhere?

### ISSUE THREAD

**Issue by Weyaaron** [flairNLP/fundus#298]
### Question

During the work on #297 I noticed that filtering for a date is not as easy as I hoped. I ended up with this unwieldy code:
```python
def date_filter(extracted: Dict[str, Any]) -> bool:
    article_date = extracted.get("publishing_date")
    if article_date:
        if article_date.tzinfo is not None and article_date.tzinfo.utcoffset(article_date) is not None:
            return today(article_date.tzinfo) - timedelta(days=1) <= article_date <= today(tzinfo=article_date.tzinfo)
        else:
            print(f"Article date {article_date} has no timezone information")
            return False

    print(f"Article date {article_date} is None")
    return False
```
Most of its deficiencies are a consequence of the fact that the users can't rely on fundus producing timezone aware objects. We should probably fix this is fundus instead of dealing with it it downstream.

**Comment by MaxDall** [comment]
I think enforcing time zones is some kind of "opening Pandora's box" here. We can not reliably enforce time zones without
- setting timezone info for every publisher, which would lead to a whole bag of other problems
or
- dropping articles without time zone info (That would block publishers without timezone info from Fundus which is a bad deal IMO)

Maybe this isn't that of a deal in the end. Regarding the filter you mentioned: An way easier fix would be to compare `date` rather than `datetime`. Judging by the comparison within your filter the timezone info isn't necessary at all.
