### ISSUE TITLE
[Feature Request]: Pretty print for PublisherCollection

### ISSUE THREAD

**Issue by alanakbik** [flairNLP/fundus#345]
### Problem statement

One of the first items in tutorial 1 is the introduction of the PublisherCollection. 

```python
from fundus import PublisherCollection

PublisherCollection.us
```

For better transparency, it would be great if one could print a PublisherCollection and get a nice printout. 

I.e. this should work: 

```python
print(PublisherCollection.us)
print(PublisherCollection.de)
print(PublisherCollection)
```

### Solution

Some printout that contains the number of sources and a (potentially truncated) list of sources. 

Something like: 
```python
print([source for source in PublisherCollection.us]) 
```

**Comment by MaxDall** [comment]
Sounds like a good idea to me. I will try to make this happen but that could be somewhat complicated because the `PublisherCollection` is built on top of Python's `Enum` implementation and to do that I would have to overwrite the `__str__` dunder method of `EnumMeta` and currently I have no idea how to do that. Let's see how that goes.
